### ISSUE TITLE
client not showing in tlauncher versions

### ISSUE THREAD

**Issue by broski12312** [WitheredKnights/riseCrack#1]
client name didnt show up in version selector thingy. when i checked versions folder it shows riseclient error version
![image](https://github.com/WitheredKnights/riseCrack/assets/158988290/e26e859c-f511-443f-b91b-b6b52c592ef8)

**Comment by AungChanPaing** [comment]
don't use tlauncher, use tlegacy

**Comment by AungChanPaing** [comment]
also, join the discord, support is faster there

**Comment by PrimeTDMomega** [comment]
Rise does not work with TLauncher due how tlauncher handles file corruption checks. TLegacy works more conventionally similar to how the Official Minecraft Launcher works. 
TLegacy - https://llaun.ch/en
Discord - https://discord.gg/Eh2jHCmxKM

ALSO
@AungChanPaing THX for lending support <3

**Comment by AungChanPaing** [comment]
np
